myproject/product/views.py
from flask import Blueprint,render_template,jsonify
from myproject.models import Product

product_blueprint = Blueprint("product",__name__,template_folder="templates/product")

@product_blueprint.route("/<int:id>")
def product(id):
    related_products = Product.query.all()
    product = Product.query.get(id)
    return render_template("product-detail.html",product=product,related_products=related_products)

@product_blueprint.route("/getInfo/<int:id>")
def getInfo(id):
    product = Product.query.get(id)
    print(jsonify(product.kwargs))

myproject/templates/macro.html
{% macro products(product_list) %}
    {%  if product_list|length >= 4 %}
    <div class="row align-items-center product-slider product-slider-4">
    {% else %}
    <div class="row align-items-center product-slider">
    {%  endif %}
        {% for product in product_list %}
            <div class="col-lg-3">
                <div class="product-item">
                    <div class="product-title">
                        <a href="product-detail.html">{{product.name}}</a>
                        <div class="ratting">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                    </div>
                    <div class="product-image">
                        <a style="position: relative;" href="product-detail.html">
                            <img src="{{url_for('static',filename='uploads/'+product.image)}}" alt="Product Image">
                            <div class="progressivebar"><p>200KG/100KG</p>
                            </div>
                        </a>
                        <div class="product-action">
                            <a onclick="addToCart({{ product.id }})"><i class="fa fa-cart-plus"></i></a>
                            <a onclick="addToWish({{ product.id }})"><i class="fa fa-heart"></i></a>
                            <a href="{{url_for('product.product',id=product.id)}}"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                    <div class="product-price">
                        <a href="{{url_for('product.product',id=product.id)}}"><h2>Details</h2></a>

                        <h3><span>$</span>99</h3>
                        <a class="btn" href="cart.html"><i class="fa fa-shopping-cart"></i>Buy Now</a>
                    </div>
                    <div id="progress" style="height:20px">
                            <div class="progress-bar progress-bar-striped" style="width:{{product.sold_quantity/product.quantity*100}}%; height:20px">{{product.sold_quantity/product.quantity*100}}%</div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endmacro %}

{% macro category_products(product_list) %}
    {% for product in product_list %}
        <div class="col-lg-3">
            <div class="product-item">
                <div class="product-title">
                    <a href="product-detail.html">{{product.name}}</a>
                    <div class="ratting">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                </div>
                <div class="product-image">
                    <a style="position: relative;" href="product-detail.html">
                        <img src="{{url_for('static',filename='uploads/'+product.image)}}" alt="Product Image">
                        <div class="progressivebar"><p>200KG/100KG</p>
                        </div>
                    </a>
                    <div class="product-action">
                        <a href="cart.html"><i class="fa fa-cart-plus"></i></a>
                        <a href="wishlist.html"><i class="fa fa-heart"></i></a>
                        <a href="{{url_for('product.product',id=product.id)}}"><i class="fa fa-search"></i></a>
                    </div>
                </div>
                <div class="product-price">
                    <a href="{{url_for('product.product',id=product.id)}}"><h2>Details</h2></a>

                    <h3><span>$</span>99</h3>
                    <a class="btn" href="cart.html"><i class="fa fa-shopping-cart"></i>Buy Now</a>
                </div>
                <div id="progress" style="height:20px">
                        <div class="progress-bar progress-bar-striped" style="width:{{product.sold_quantity/product.quantity*100}}%; height:20px">{{product.sold_quantity/product.quantity*100}}%</div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endmacro %}